# Generated by Django 2.2.12 on 2020-12-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plaintes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=50)),
            ],
        ),
    ]
